modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/CreativeMD/EnhancedVisuals/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="enhancedvisuals"
    logoFile="enhancedvisuals.png"
    version="1.7.1"
    displayName="EnhancedVisuals"
    displayURL="https://modrinth.com/mod/enhancedvisuals"
    authors="CreativeMD, Sonicjumper"
    description='''Experience realism and extra video effects for your in-game experience.'''

[[dependencies.enhancedvisuals]]
    modId="neoforge"
    type="required"
    versionRange="[20.6,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.enhancedvisuals]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.enhancedvisuals]]
   modId="creativecore"
   type="required"
   ordering="NONE"
   side="BOTH"
   versionRange="[2.11.5,)"

[[mixins]]
   config="enhancedvisuals.mixins.json"

